export default {
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_KEY: 'INVALID_KEY',
  INVALID_ORGANIZATION: 'INVALID_ORGANIZATION',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_VALUE: 'INVALID_VALUE',
  NO_USER: 'NO_USER',
  USER_DUPLICATE_EMAIL: 'USER_DUPLICATE_EMAIL',
  USER_DUPLICATE_USERNAME: 'USER_DUPLICATE_USERNAME',
  UNKNOWN: 'UNKNOWN'
}
