export default {
  INVALID_KEY: 'INVALID_KEY',
  INVALID_VALUE: 'INVALID_VALUE',
  NO_USER: 'NO_USER',
  USER_DUPLICATE_EMAIL: 'USER_DUPLICATE_EMAIL',
  USER_DUPLICATE_USERNAME: 'USER_DUPLICATE_USERNAME',
  UNKNOWN: 'UNKNOWN'
}
